# Generated by Django 5.0.2 on 2024-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
